#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
TOTAL_MINUTES=8
ENV_FILE="${EVENT_CONTROL_ENV_FILE:-deploy/event-control.env}"

remote_control() {
  local command_name="$1" argument="${2:-}" confirmation="${3:-}"
  ssh -i "$EVENT_SSH_KEY" -o IdentitiesOnly=yes -o BatchMode=yes \
    -o StrictHostKeyChecking=yes "$EVENT_USER@$EVENT_HOST" \
    "sh -s -- '$EVENT_DEPLOY_PATH' '$command_name' '$argument' '$confirmation'" \
    < deploy/remote-event-control.sh
}

remote_reset_replay() {
  local fixture_id="$1"
  ssh -i "$EVENT_SSH_KEY" -o IdentitiesOnly=yes -o BatchMode=yes \
    -o StrictHostKeyChecking=yes "$EVENT_USER@$EVENT_HOST" \
    "sh -s -- '$EVENT_DEPLOY_PATH' '$fixture_id' 'RESET $fixture_id'" \
    < deploy/remote-reset-replay.sh
}

banner "SABG event control"

stage "Connection" 1
if [[ ! -f "$ENV_FILE" ]]; then
  say "First run: connection settings stay only in the git-ignored local config."
  ask EVENT_HOST "VPS host or IP:"
  ask EVENT_USER "SSH user:"
  ask EVENT_DEPLOY_PATH "Absolute deploy path:"
  ask EVENT_SSH_KEY "Absolute private SSH key path:"
  [[ -n "$EVENT_HOST" && -n "$EVENT_USER" && -n "$EVENT_DEPLOY_PATH" && -n "$EVENT_SSH_KEY" ]] \
    || { warn "all connection settings are required"; exit 1; }
  write_env EVENT_HOST "$EVENT_HOST"
  write_env EVENT_USER "$EVENT_USER"
  write_env EVENT_DEPLOY_PATH "$EVENT_DEPLOY_PATH"
  write_env EVENT_SSH_KEY "$EVENT_SSH_KEY"
  chmod 0600 "$ENV_FILE"
fi
EVENT_HOST=$(_existing EVENT_HOST)
EVENT_USER=$(_existing EVENT_USER)
EVENT_DEPLOY_PATH=$(_existing EVENT_DEPLOY_PATH)
EVENT_SSH_KEY=$(_existing EVENT_SSH_KEY)
[[ "$EVENT_HOST" =~ ^[A-Za-z0-9:._-]+$ ]] || { warn "invalid EVENT_HOST"; exit 1; }
[[ "$EVENT_USER" =~ ^[A-Za-z0-9._-]+$ ]] || { warn "invalid EVENT_USER"; exit 1; }
[[ "$EVENT_DEPLOY_PATH" =~ ^/[A-Za-z0-9._/-]+$ ]] || { warn "invalid EVENT_DEPLOY_PATH"; exit 1; }
[[ -f "$EVENT_SSH_KEY" ]] || { warn "SSH key not found: $EVENT_SSH_KEY"; exit 1; }
say "Connected configuration loaded from $ENV_FILE."

stage "Current status" 1
status_output=$(remote_control status)
printf '%s\n' "$status_output"

stage "Choose operation" 1
printf '  1. Show status only\n'
printf '  2. Reset replay rehearsal\n'
printf '  3. Discover nearest match and go live\n'
printf '  4. Show recent app logs\n'
printf '  Select [1-4]: '
read -r action

stage "Execute" 5
case "$action" in
  1)
    say "No changes requested."
    ;;
  2)
    current_source=$(printf '%s\n' "$status_output" | grep '^SOURCE=' | cut -d= -f2-)
    [[ "$current_source" == replay ]] || { warn "replay reset is unavailable while source is $current_source"; exit 1; }
    replay_fixture=$(printf '%s\n' "$status_output" | grep '^REPLAY_FIXTURE_ID=' | cut -d= -f2-)
    case "$replay_fixture" in
      18179764|18241006) ;;
      *) warn "deployed replay fixture is unavailable"; exit 1 ;;
    esac
    confirm "Reset replay fixture $replay_fixture and start a fresh lobby?" || exit 0
    remote_reset_replay "$replay_fixture"
    ;;
  3)
    discovery_output=$(remote_control discover-live)
    printf '%s\n' "$discovery_output"
    marker=$(printf '%s\n' "$discovery_output" | grep '^SABG_LIVE_FIXTURE=' | tail -n1)
    [[ -n "$marker" ]] || { warn "live discovery did not return a fixture"; exit 1; }
    payload=${marker#SABG_LIVE_FIXTURE=}
    fixture_json=$(node -e 'process.stdout.write(Buffer.from(process.argv[1], "base64url").toString("utf8"))' "$payload")
    fixture_id=$(printf '%s' "$fixture_json" | jq -r '.fixtureId')
    home_team=$(printf '%s' "$fixture_json" | jq -r '.homeTeam')
    away_team=$(printf '%s' "$fixture_json" | jq -r '.awayTeam')
    start_time=$(printf '%s' "$fixture_json" | jq -r '.startTime')
    say "Nearest match: $home_team vs $away_team"
    say "Kickoff: $start_time"
    printf '  Type GO LIVE %s to confirm: ' "$fixture_id"
    read -r live_confirmation
    [[ "$live_confirmation" == "GO LIVE $fixture_id" ]] || { warn "confirmation did not match"; exit 1; }
    remote_control switch-live "$fixture_id" "$live_confirmation"
    ;;
  4)
    remote_control logs
    ;;
  *)
    warn "unknown selection"
    exit 1
    ;;
esac

finish
