#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
TOTAL_MINUTES=6
ENV_FILE="${EVENT_CONTROL_ENV_FILE:-deploy/event-control.env}"

_TUI_CURSOR_HIDDEN=false
_DISCOVERY_FILE=""

restore_event_control() {
  if [[ "$_TUI_CURSOR_HIDDEN" == true ]] && [[ -t 1 ]] && command -v tput >/dev/null 2>&1; then
    tput cnorm || true
  fi
  _TUI_CURSOR_HIDDEN=false
  [[ -z "$_DISCOVERY_FILE" ]] || rm -f "$_DISCOVERY_FILE"
}

trap restore_event_control EXIT
trap 'exit 130' HUP INT TERM

hide_cursor() {
  if [[ -t 1 ]] && command -v tput >/dev/null 2>&1; then
    tput civis || true
    _TUI_CURSOR_HIDDEN=true
  fi
}

show_cursor() {
  if [[ "$_TUI_CURSOR_HIDDEN" == true ]] && [[ -t 1 ]] && command -v tput >/dev/null 2>&1; then
    tput cnorm || true
  fi
  _TUI_CURSOR_HIDDEN=false
}

remote_control() {
  local command_name="$1" argument="${2:-}" confirmation="${3:-}"
  ssh -i "$EVENT_SSH_KEY" -o IdentitiesOnly=yes -o BatchMode=yes \
    -o StrictHostKeyChecking=yes "$EVENT_USER@$EVENT_HOST" \
    "sh -s -- '$EVENT_DEPLOY_PATH' '$command_name' '$argument' '$confirmation'" \
    < deploy/remote-event-control.sh
}

status_value() {
  local target_key="$1" line
  while IFS= read -r line; do
    [[ "${line%%=*}" == "$target_key" ]] || continue
    printf '%s' "${line#*=}"
    return 0
  done <<< "$status_output"
  return 1
}

read_menu_key() {
  local key rest=""
  IFS= read -rsn1 key || return 1
  if [[ "$key" == $'\e' ]]; then
    IFS= read -rsn2 -t 0.1 rest || true
    case "$rest" in
      '[A') printf 'up' ;;
      '[B') printf 'down' ;;
      '') printf 'cancel' ;;
      *) printf 'ignore' ;;
    esac
    return 0
  fi
  case "$key" in
    '') printf 'select' ;;
    q|Q) printf 'cancel' ;;
    k|K) printf 'up' ;;
    j|J) printf 'down' ;;
    *) printf 'ignore' ;;
  esac
}

TOURNAMENT_IDS=()
TOURNAMENT_NAMES=()
TOURNAMENT_COUNTS=()
ALL_SERIES_IDS=()
ALL_SERIES_TOURNAMENT_IDS=()
ALL_SERIES_TEAMS=()
ALL_SERIES_SCHEDULES=()
ALL_SERIES_FORMATS=()
ALL_SERIES_STATES=()
ALL_SERIES_REASONS=()

decode_discovery() {
  local payload="$1" kind first second third fourth fifth sixth seventh
  _DISCOVERY_FILE=$(mktemp)
  node - "$payload" > "$_DISCOVERY_FILE" <<'NODE'
const payload = JSON.parse(Buffer.from(process.argv[2], "base64url").toString("utf8"));
if (!payload || !Array.isArray(payload.series)) throw new Error("Discovery payload has no Series array");
const clean = (value) => String(value).replace(/[\u0000-\u001f\u007f|]/g, " ").trim() || "-";
const safeId = (value) => {
  const id = String(value);
  if (!/^[A-Za-z0-9._:-]{1,200}$/.test(id)) throw new Error(`Unsafe GRID ID: ${id}`);
  return id;
};
const formatter = new Intl.DateTimeFormat(undefined, {
  month: "short",
  day: "numeric",
  hour: "2-digit",
  minute: "2-digit",
});
const tournaments = new Map();
for (const series of payload.series) {
  const tournamentId = safeId(series.competition?.gridTournamentId);
  const current = tournaments.get(tournamentId) ?? { name: clean(series.competition?.name), count: 0 };
  current.count += 1;
  tournaments.set(tournamentId, current);
}
for (const [id, tournament] of tournaments) {
  process.stdout.write(["T", id, tournament.name, tournament.count].join("|") + "\n");
}
for (const series of payload.series) {
  const id = safeId(series.gridSeriesId);
  const tournamentId = safeId(series.competition?.gridTournamentId);
  const teams = Array.isArray(series.teams) ? series.teams : [];
  const firstTeam = clean(teams[0]?.shortName ?? teams[0]?.name ?? "TBD");
  const secondTeam = clean(teams[1]?.shortName ?? teams[1]?.name ?? "TBD");
  const start = new Date(series.scheduledStartTime);
  if (Number.isNaN(start.getTime())) throw new Error(`Invalid schedule for GRID Series ${id}`);
  const state = series.selection?.state === "selectable" ? "selectable" : "disabled";
  const reason = state === "selectable" ? "-" : clean(series.selection?.reason ?? "UNAVAILABLE");
  process.stdout.write([
    "S",
    id,
    tournamentId,
    `${firstTeam} vs ${secondTeam}`,
    formatter.format(start),
    `Bo${Number(series.format)}`,
    state,
    reason,
  ].join("|") + "\n");
}
NODE

  while IFS='|' read -r kind first second third fourth fifth sixth seventh; do
    case "$kind" in
      T)
        TOURNAMENT_IDS+=("$first")
        TOURNAMENT_NAMES+=("$second")
        TOURNAMENT_COUNTS+=("$third")
        ;;
      S)
        ALL_SERIES_IDS+=("$first")
        ALL_SERIES_TOURNAMENT_IDS+=("$second")
        ALL_SERIES_TEAMS+=("$third")
        ALL_SERIES_SCHEDULES+=("$fourth")
        ALL_SERIES_FORMATS+=("$fifth")
        ALL_SERIES_STATES+=("$sixth")
        ALL_SERIES_REASONS+=("$seventh")
        ;;
    esac
  done < "$_DISCOVERY_FILE"
  rm -f "$_DISCOVERY_FILE"
  _DISCOVERY_FILE=""
  [[ ${#TOURNAMENT_IDS[@]} -gt 0 ]] || { warn "GRID returned no CS2 tournaments in the discovery window"; return 1; }
}

select_tournament() {
  local index=0 key row
  hide_cursor
  while true; do
    _clear
    printf '\n%s%s  Select CS2 tournament%s\n' "$BOLD" "$BLUE" "$RESET"
    printf '%s  ↑/↓ move · Enter select · q/Esc cancel%s\n\n' "$DIM" "$RESET"
    for row in "${!TOURNAMENT_IDS[@]}"; do
      if [[ "$row" -eq "$index" ]]; then
        printf '  %s%s› %-42s %3s Series%s\n' "$BOLD" "$GREEN" "${TOURNAMENT_NAMES[$row]}" "${TOURNAMENT_COUNTS[$row]}" "$RESET"
      else
        printf '    %-42s %3s Series\n' "${TOURNAMENT_NAMES[$row]}" "${TOURNAMENT_COUNTS[$row]}"
      fi
    done
    key=$(read_menu_key) || { show_cursor; return 1; }
    case "$key" in
      up) index=$(( (index - 1 + ${#TOURNAMENT_IDS[@]}) % ${#TOURNAMENT_IDS[@]} )) ;;
      down) index=$(( (index + 1) % ${#TOURNAMENT_IDS[@]} )) ;;
      select) SELECTED_TOURNAMENT_INDEX=$index; show_cursor; return 0 ;;
      cancel) show_cursor; return 1 ;;
    esac
  done
}

select_series() {
  local tournament_id="$1" index=0 key row reason
  SERIES_IDS=()
  SERIES_TEAMS=()
  SERIES_SCHEDULES=()
  SERIES_FORMATS=()
  SERIES_STATES=()
  SERIES_REASONS=()
  for row in "${!ALL_SERIES_IDS[@]}"; do
    [[ "${ALL_SERIES_TOURNAMENT_IDS[$row]}" == "$tournament_id" ]] || continue
    SERIES_IDS+=("${ALL_SERIES_IDS[$row]}")
    SERIES_TEAMS+=("${ALL_SERIES_TEAMS[$row]}")
    SERIES_SCHEDULES+=("${ALL_SERIES_SCHEDULES[$row]}")
    SERIES_FORMATS+=("${ALL_SERIES_FORMATS[$row]}")
    SERIES_STATES+=("${ALL_SERIES_STATES[$row]}")
    SERIES_REASONS+=("${ALL_SERIES_REASONS[$row]}")
  done
  [[ ${#SERIES_IDS[@]} -gt 0 ]] || return 1

  hide_cursor
  while true; do
    _clear
    printf '\n%s%s  Select Series · %s%s\n' "$BOLD" "$BLUE" "${TOURNAMENT_NAMES[$SELECTED_TOURNAMENT_INDEX]}" "$RESET"
    printf '%s  ↑/↓ move · Enter select · q/Esc cancel%s\n\n' "$DIM" "$RESET"
    for row in "${!SERIES_IDS[@]}"; do
      reason="${SERIES_REASONS[$row]}"
      [[ "$reason" == PARTICIPANTS_INCOMPLETE ]] && reason="TBD"
      [[ "$reason" == FULL_LIVE_DATA_UNAVAILABLE ]] && reason="NO LIVE DATA"
      if [[ "${SERIES_STATES[$row]}" == disabled ]]; then
        printf '%s' "$DIM"
      fi
      if [[ "$row" -eq "$index" ]]; then
        printf '  %s%s› %-34s %-17s %-4s  %s%s\n' "$BOLD" "$GREEN" "${SERIES_TEAMS[$row]}" "${SERIES_SCHEDULES[$row]}" "${SERIES_FORMATS[$row]}" "$reason" "$RESET"
      else
        printf '    %-34s %-17s %-4s  %s%s\n' "${SERIES_TEAMS[$row]}" "${SERIES_SCHEDULES[$row]}" "${SERIES_FORMATS[$row]}" "$reason" "$RESET"
      fi
    done
    key=$(read_menu_key) || { show_cursor; return 1; }
    case "$key" in
      up) index=$(( (index - 1 + ${#SERIES_IDS[@]}) % ${#SERIES_IDS[@]} )) ;;
      down) index=$(( (index + 1) % ${#SERIES_IDS[@]} )) ;;
      select)
        if [[ "${SERIES_STATES[$index]}" == selectable ]]; then
          SELECTED_SERIES_INDEX=$index
          show_cursor
          return 0
        fi
        ;;
      cancel) show_cursor; return 1 ;;
    esac
  done
}

banner "SABG CS2 event control"

stage "Connection" 1
if [[ ! -f "$ENV_FILE" ]]; then
  say "First run: connection settings stay only in the git-ignored local config."
  ask EVENT_HOST "VPS host or IP:"
  ask EVENT_USER "SSH user:"
  ask EVENT_DEPLOY_PATH "Absolute deploy path:"
  ask EVENT_SSH_KEY "Absolute private SSH key path:"
  [[ -n "$EVENT_HOST" && -n "$EVENT_USER" && -n "$EVENT_DEPLOY_PATH" && -n "$EVENT_SSH_KEY" ]] \
    || { warn "all connection settings are required"; exit 1; }
  write_env EVENT_HOST "$EVENT_HOST"
  write_env EVENT_USER "$EVENT_USER"
  write_env EVENT_DEPLOY_PATH "$EVENT_DEPLOY_PATH"
  write_env EVENT_SSH_KEY "$EVENT_SSH_KEY"
  chmod 0600 "$ENV_FILE"
fi
EVENT_HOST=$(_existing EVENT_HOST)
EVENT_USER=$(_existing EVENT_USER)
EVENT_DEPLOY_PATH=$(_existing EVENT_DEPLOY_PATH)
EVENT_SSH_KEY=$(_existing EVENT_SSH_KEY)
[[ "$EVENT_HOST" =~ ^[A-Za-z0-9:._-]+$ ]] || { warn "invalid EVENT_HOST"; exit 1; }
[[ "$EVENT_USER" =~ ^[A-Za-z0-9._-]+$ ]] || { warn "invalid EVENT_USER"; exit 1; }
[[ "$EVENT_DEPLOY_PATH" =~ ^/[A-Za-z0-9._/-]+$ ]] || { warn "invalid EVENT_DEPLOY_PATH"; exit 1; }
[[ -f "$EVENT_SSH_KEY" ]] || { warn "SSH key not found: $EVENT_SSH_KEY"; exit 1; }
command -v node >/dev/null 2>&1 || { warn "Node.js is required to decode GRID discovery"; exit 1; }
say "Connected configuration loaded from $ENV_FILE."

stage "Current status" 1
status_output=$(remote_control status)
printf '%s\n' "$status_output"
current_mode=$(status_value MODE || printf 'unknown')
active_series=$(status_value SERIES_ID || true)
app_health=$(status_value APP_HEALTH || printf 'unknown')

stage "Choose operation" 1
say "Mode: $current_mode · App health: $app_health"
[[ -z "$active_series" ]] || say "Active Series: $active_series"
printf '  1. Show CS2 status only\n'
printf '  2. Select tournament and start Series\n'
printf '  3. Stop active Series\n'
printf '  4. Show recent CS2 logs\n'
printf '  Select [1-4]: '
read -r action

stage "Execute" 3
case "$action" in
  1)
    printf '%s\n' "$status_output"
    ;;
  2)
    [[ "$current_mode" == catalog ]] || { warn "stop active Series $active_series before selecting another"; exit 1; }
    discovery_output=$(remote_control discover-cs2)
    marker=""
    while IFS= read -r line; do
      [[ "$line" == SABG_CS2_DISCOVERY=* ]] && marker=${line#SABG_CS2_DISCOVERY=}
    done <<< "$discovery_output"
    [[ -n "$marker" ]] || { warn "GRID discovery did not return a CS2 payload"; exit 1; }
    decode_discovery "$marker"
    select_tournament || { say "Selection cancelled."; exit 0; }
    selected_tournament_id=${TOURNAMENT_IDS[$SELECTED_TOURNAMENT_INDEX]}
    select_series "$selected_tournament_id" || { say "Selection cancelled."; exit 0; }
    selected_series_id=${SERIES_IDS[$SELECTED_SERIES_INDEX]}
    say "Tournament: ${TOURNAMENT_NAMES[$SELECTED_TOURNAMENT_INDEX]}"
    say "Series: ${SERIES_TEAMS[$SELECTED_SERIES_INDEX]}"
    say "Schedule: ${SERIES_SCHEDULES[$SELECTED_SERIES_INDEX]} · ${SERIES_FORMATS[$SELECTED_SERIES_INDEX]}"
    printf '  Type START CS2 %s to confirm: ' "$selected_series_id"
    read -r start_confirmation
    [[ "$start_confirmation" == "START CS2 $selected_series_id" ]] || { warn "confirmation did not match"; exit 1; }
    remote_control start-cs2 "$selected_series_id" "$start_confirmation"
    ;;
  3)
    if [[ "$current_mode" == catalog ]]; then
      say "CS2 runtime is already catalog-only."
      exit 0
    fi
    [[ "$current_mode" == live && "$active_series" =~ ^[A-Za-z0-9._:-]+$ ]] \
      || { warn "active CS2 Series is unavailable"; exit 1; }
    printf '  Type STOP CS2 %s to confirm: ' "$active_series"
    read -r stop_confirmation
    [[ "$stop_confirmation" == "STOP CS2 $active_series" ]] || { warn "confirmation did not match"; exit 1; }
    remote_control stop-cs2 "$active_series" "$stop_confirmation"
    ;;
  4)
    remote_control logs
    ;;
  *)
    warn "unknown selection"
    exit 1
    ;;
esac

pause "Press Enter to finish."
finish
